# testingss

name: paperjam-develop CD
on:
  push:
    branches: [docker-develop-pipeline]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL_DEV }}" > .env
          echo "NEXT_PUBLIC_WS_URL=${{ secrets.NEXT_PUBLIC_WS_URL_DEV }}" >> .env
      - name: Install Packages
        run: yarn install

      - name: Print .next
        run: cat ./node_modules/.bin/next

      - name: List file
        run: ls -la

      - name: Generate deployment package
        run: zip -r deploy.zip . -x .git ./node_modules

      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: "-"
          flags: "g"
      - name: Beanstalk Deploy for app
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_ADMIN_APP_KEY_ID}}
          aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_ADMIN_APP_KEY}}
          application_name: "paperjam"
          environment_name: "docker-develop-web"
          region: "us-west-1"
          version_label: "docker-develop-web-${{ steps.format-time.outputs.replaced }}"
          deployment_package: deploy.zip
      - name: Deployed!
        run: echo App deployed to ELB
